In [2]:
from numpy import array
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers.core import Activation, Dropout, Dense
from keras.layers import Flatten, LSTM
from keras.layers import GlobalMaxPooling1D
from keras.models import Model
from keras.layers.embeddings import Embedding
from sklearn.model_selection import train_test_split
from keras.preprocessing.text import Tokenizer
from keras.layers import Input
from keras.layers.merge import Concatenate
from keras.layers import Bidirectional

In [3]:
import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt
%matplotlib inline

In [6]:
x = list()
y = list()
x = [x+3 for x in range(-2, 43, 3)]

for i in x:
    output_vector = list()
    output_vector.append(i+1)
    output_vector.append(i+2)
    output_vector.append(i+3)
    output_vector.append(i+4)
    y.append(output_vector)
    
print(x)
print(y)

[1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43]
[[2, 3, 4, 5], [5, 6, 7, 8], [8, 9, 10, 11], [11, 12, 13, 14], [14, 15, 16, 17], [17, 18, 19, 20], [20, 21, 22, 23], [23, 24, 25, 26], [26, 27, 28, 29], [29, 30, 31, 32], [32, 33, 34, 35], [35, 36, 37, 38], [38, 39, 40, 41], [41, 42, 43, 44], [44, 45, 46, 47]]


In [7]:
print(len(x))
print(len(y))

15
15


In [8]:
x = np.array(x)
y = np.array(y)

In [12]:
x = x.reshape(15, 1, 1)
y = y

In [14]:
x.shape

(15, 1, 1)

In [27]:
#Solution via simple LSTM
model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(1, 1)))
model.add(Dense(4))
model.compile(optimizer='adam', loss='mse')
model.summary()

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_6 (LSTM)                (None, 50)                10400     
_________________________________________________________________
dense_6 (Dense)              (None, 4)                 204       
Total params: 10,604
Trainable params: 10,604
Non-trainable params: 0
_________________________________________________________________


In [28]:
model.fit(x,y, epochs=1000, validation_split=0.2, batch_size=3)

Train on 12 samples, validate on 3 samples
Epoch 1/1000
12/12 [==============================] - 1s 88ms/step - loss: 505.3441 - val_loss: 1785.6581
Epoch 2/1000
12/12 [==============================] - 0s 5ms/step - loss: 501.4322 - val_loss: 1774.2592
Epoch 3/1000
12/12 [==============================] - 0s 3ms/step - loss: 497.9316 - val_loss: 1762.0785
Epoch 4/1000
12/12 [==============================] - 0s 4ms/step - loss: 495.0551 - val_loss: 1748.8011
Epoch 5/1000
12/12 [==============================] - 0s 3ms/step - loss: 490.8645 - val_loss: 1735.1364
Epoch 6/1000
12/12 [==============================] - 0s 5ms/step - loss: 486.6457 - val_loss: 1720.4996
Epoch 7/1000
12/12 [==============================] - 0s 4ms/step - loss: 482.0788 - val_loss: 1704.6615
Epoch 8/1000
12/12 [==============================] - 0s 3ms/step - loss: 477.3661 - val_loss: 1686.8453
Epoch 9/1000
12/12 [==============================] - 0s 6ms/step - loss: 471.7288 - val_loss: 1667.4263
Epoch 10/10

In [29]:
test_input = array([10])
test_input = test_input.reshape((1, 1, 1))
test_output = model.predict(test_input, verbose=0)
print(test_output)

[[10.962414 12.009826 13.119372 14.175141]]


In [30]:
# One to many sequence problems with multiple features
# where input samples will have one time step but two features. output will be a vector of two elements

### One to Many sequence problem with multiple features

In [52]:
nums = 25

X1 = list()
X2 = list()
X = list()
Y = list()

X1 = [(x+1)*2 for x in range(25)]
X2 = [(x+1)*3 for x in range(25)]

for x1, x2 in zip(X1, X2):
    output_vector = list()
    output_vector.append(x1+1)
    output_vector.append(x1+2)
    output_vector.append(x2+1)
    output_vector.append(x2+2)
    Y.append(output_vector)

X = np.column_stack((X1, X2))
print(Y)
print(X)
print(len(X), len(Y))

[[3, 4, 4, 5], [5, 6, 7, 8], [7, 8, 10, 11], [9, 10, 13, 14], [11, 12, 16, 17], [13, 14, 19, 20], [15, 16, 22, 23], [17, 18, 25, 26], [19, 20, 28, 29], [21, 22, 31, 32], [23, 24, 34, 35], [25, 26, 37, 38], [27, 28, 40, 41], [29, 30, 43, 44], [31, 32, 46, 47], [33, 34, 49, 50], [35, 36, 52, 53], [37, 38, 55, 56], [39, 40, 58, 59], [41, 42, 61, 62], [43, 44, 64, 65], [45, 46, 67, 68], [47, 48, 70, 71], [49, 50, 73, 74], [51, 52, 76, 77]]
[[ 2  3]
 [ 4  6]
 [ 6  9]
 [ 8 12]
 [10 15]
 [12 18]
 [14 21]
 [16 24]
 [18 27]
 [20 30]
 [22 33]
 [24 36]
 [26 39]
 [28 42]
 [30 45]
 [32 48]
 [34 51]
 [36 54]
 [38 57]
 [40 60]
 [42 63]
 [44 66]
 [46 69]
 [48 72]
 [50 75]]
25 25


In [56]:
X = np.array(X).reshape(25,1,2)
Y = np.array(Y)

In [57]:
#LSTM model
model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(1, 2)))
model.add(Dense(4))
model.compile(optimizer='adam', loss='mse')
model.summary()

Model: "sequential_9"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_9 (LSTM)                (None, 50)                10600     
_________________________________________________________________
dense_9 (Dense)              (None, 4)                 204       
Total params: 10,804
Trainable params: 10,804
Non-trainable params: 0
_________________________________________________________________


In [58]:
model.fit(X, Y, epochs=1000, validation_split=0.2, batch_size=3)

Train on 20 samples, validate on 5 samples
Epoch 1/1000
20/20 [==============================] - 1s 56ms/step - loss: 982.6026 - val_loss: 3407.7943
Epoch 2/1000
20/20 [==============================] - 0s 2ms/step - loss: 933.9209 - val_loss: 3246.7770
Epoch 3/1000
20/20 [==============================] - 0s 3ms/step - loss: 893.9639 - val_loss: 3078.7914
Epoch 4/1000
20/20 [==============================] - 0s 2ms/step - loss: 841.4932 - val_loss: 2875.0521
Epoch 5/1000
20/20 [==============================] - 0s 2ms/step - loss: 782.8498 - val_loss: 2622.1352
Epoch 6/1000
20/20 [==============================] - 0s 4ms/step - loss: 713.7200 - val_loss: 2326.6216
Epoch 7/1000
20/20 [==============================] - 0s 2ms/step - loss: 627.3912 - val_loss: 1998.1072
Epoch 8/1000
20/20 [==============================] - 0s 6ms/step - loss: 545.8756 - val_loss: 1629.5875
Epoch 9/1000
20/20 [==============================] - 0s 4ms/step - loss: 458.9224 - val_loss: 1293.3834
Epoch 10/10

In [59]:
test_input = array([40, 60])
test_input = test_input.reshape((1, 1, 2))
test_output = model.predict(test_input, verbose=0)
print(test_output)

[[41.01727  42.026203 61.03103  62.037132]]


In [61]:
# Solution via stacked LSTM
model = Sequential()
model.add(LSTM(50, activation='relu', return_sequences=True, input_shape=(1,2)))
model.add(LSTM(50, activation='relu'))
model.add(Dense(4))
model.compile(optimizer='adam', loss='mse')
model.summary()

Model: "sequential_11"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_12 (LSTM)               (None, 1, 50)             10600     
_________________________________________________________________
lstm_13 (LSTM)               (None, 50)                20200     
_________________________________________________________________
dense_11 (Dense)             (None, 4)                 204       
Total params: 31,004
Trainable params: 31,004
Non-trainable params: 0
_________________________________________________________________


In [62]:
history = model.fit(X, Y, epochs=1000, validation_split=0.2, verbose=1, batch_size=3)

Train on 20 samples, validate on 5 samples
Epoch 1/1000
20/20 [==============================] - 2s 95ms/step - loss: 1004.2690 - val_loss: 3567.1625
Epoch 2/1000
20/20 [==============================] - 0s 5ms/step - loss: 992.2079 - val_loss: 3510.9013
Epoch 3/1000
20/20 [==============================] - 0s 5ms/step - loss: 972.0341 - val_loss: 3424.5515
Epoch 4/1000
20/20 [==============================] - 0s 7ms/step - loss: 943.8668 - val_loss: 3250.5371
Epoch 5/1000
20/20 [==============================] - 0s 5ms/step - loss: 883.5751 - val_loss: 2914.7178
Epoch 6/1000
20/20 [==============================] - 0s 9ms/step - loss: 775.0635 - val_loss: 2356.5363
Epoch 7/1000
20/20 [==============================] - 0s 6ms/step - loss: 598.0838 - val_loss: 1550.0312
Epoch 8/1000
20/20 [==============================] - 0s 6ms/step - loss: 356.6198 - val_loss: 647.0042
Epoch 9/1000
20/20 [==============================] - 0s 6ms/step - loss: 134.3526 - val_loss: 153.5748
Epoch 10/100

In [63]:
test_input = array([40, 60])
test_input = test_input.reshape((1, 1, 2))
test_output = model.predict(test_input, verbose=0)
print(test_output)

[[40.99843  42.028233 60.98468  62.008022]]


In [64]:
# Solution via Bidirectional LSTM

In [65]:
from keras.layers import Bidirectional
model = Sequential()
model.add(Bidirectional(LSTM(50, activation='relu'), input_shape=(1,2)))
model.add(Dense(4))
model.compile(optimizer='adam', loss='mse')
model.summary()

Model: "sequential_12"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
bidirectional_1 (Bidirection (None, 100)               21200     
_________________________________________________________________
dense_12 (Dense)             (None, 4)                 404       
Total params: 21,604
Trainable params: 21,604
Non-trainable params: 0
_________________________________________________________________


In [66]:
history = model.fit(X, Y, epochs=1000, validation_split=0.2, verbose=1, batch_size=3)
test_output = model.predict(test_input, verbose=0)
print(test_output)

Train on 20 samples, validate on 5 samples
Epoch 1/1000
20/20 [==============================] - 2s 97ms/step - loss: 943.2236 - val_loss: 3331.5603
Epoch 2/1000
20/20 [==============================] - 0s 6ms/step - loss: 906.7223 - val_loss: 3195.1457
Epoch 3/1000
20/20 [==============================] - 0s 5ms/step - loss: 862.6809 - val_loss: 3011.6979
Epoch 4/1000
20/20 [==============================] - 0s 9ms/step - loss: 810.2880 - val_loss: 2774.5235
Epoch 5/1000
20/20 [==============================] - 0s 4ms/step - loss: 732.0678 - val_loss: 2470.6043
Epoch 6/1000
20/20 [==============================] - 0s 4ms/step - loss: 649.3737 - val_loss: 2065.2295
Epoch 7/1000
20/20 [==============================] - 0s 6ms/step - loss: 544.3940 - val_loss: 1634.6232
Epoch 8/1000
20/20 [==============================] - 0s 5ms/step - loss: 419.2657 - val_loss: 1189.9512
Epoch 9/1000
20/20 [==============================] - 0s 4ms/step - loss: 282.4257 - val_loss: 723.2693
Epoch 10/100